In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [6]:
df.head(10)

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
0,1000,53,Male,No,Smartphone,SKU1004,2,Cancelled,Credit Card,5538.33,791.19,7,2024-03-20,Standard,"Accessory,Accessory,Accessory",40.21
1,1000,53,Male,No,Tablet,SKU1002,3,Completed,Paypal,741.09,247.03,3,2024-04-20,Overnight,Impulse Item,26.09
2,1002,41,Male,No,Laptop,SKU1005,3,Completed,Credit Card,1855.84,463.96,4,2023-10-17,Express,NaN,0.00
3,1002,41,Male,Yes,Smartphone,SKU1004,2,Completed,Cash,3164.76,791.19,4,2024-08-09,Overnight,"Impulse Item,Impulse Item",60.16
4,1003,75,Male,Yes,Smartphone,SKU1001,5,Completed,Cash,41.50,20.75,2,2024-05-21,Express,Accessory,35.56
5,1004,41,Female,No,Smartphone,SKU1001,5,Completed,Credit Card,83.00,20.75,4,2024-05-26,Standard,"Impulse Item,Accessory",65.78
6,1005,25,Female,No,Smartwatch,SKU1003,3,Completed,Paypal,7603.47,844.83,9,2024-01-30,Overnight,NaN,0.00
7,1005,25,Female,No,Laptop,SKU1005,3,Completed,Debit Card,4175.64,463.96,9,2024-06-24,Overnight,"Extended Warranty,Extended Warranty",75.33
8,1006,24,Male,No,Smartphone,SKU1004,2,Cancelled,Debit Card,5538.33,791.19,7,2023-10-03,Standard,Impulse Item,43.05
9,1006,24,Male,Yes,Laptop,SKU1005,3,Completed,Cash,4175.64,463.96,9,2024-01-01,Express,NaN,0.00

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer ID        20000 non-null  int64
 1   Age                20000 non-null  int64
 2   Gender             19999 non-null  str
 3   Loyalty Member     20000 non-null  str
 4   Product Type       20000 non-null  str
 5   SKU                20000 non-null  str
 6   Rating             20000 non-null  int64
 7   Order Status       20000 non-null  str
 8   Payment Method     20000 non-null  str
 9   Total Price        20000 non-null  float64
 10  Unit Price         20000 non-null  float64
 11  Quantity           20000 non-null  int64
 12  Purchase Date      20000 non-null  str
 13  Shipping Type      20000 non-null  str
 14  Add-ons Purchased  15132 non-null  str
 15  Add-on Total       20000 non-null  float64
dtypes: float64(3), int64(4), str(9)
memory usage: 3.9 MB

In [8]:
df.describe(include='all')

,Customer ID,Age,Gender,Loyalty Member,Product Type,SKU,Rating,Order Status,Payment Method,Total Price,Unit Price,Quantity,Purchase Date,Shipping Type,Add-ons Purchased,Add-on Total
count,20000.000000,20000.000000,19999,20000,20000,20000,20000.000000,20000,20000,20000.000000,20000.000000,20000.000000,20000,20000,15132,20000.000000
unique,NaN,NaN,2,2,5,10,NaN,2,6,NaN,NaN,NaN,366,5,75,NaN
top,NaN,NaN,Male,No,Smartphone,TBL345,NaN,Completed,Credit Card,NaN,NaN,NaN,2024-04-26,Standard,Extended Warranty,NaN
freq,NaN,NaN,10164,15657,5978,2062,NaN,13432,5868,NaN,NaN,NaN,88,6725,1701,NaN
mean,10483.526550,48.994100,NaN,NaN,NaN,NaN,3.093950,NaN,NaN,3180.133418,578.631867,5.485550,NaN,NaN,NaN,62.244848
std,5631.732525,18.038745,NaN,NaN,NaN,NaN,1.223764,NaN,NaN,2544.978675,312.274076,2.870854,NaN,NaN,NaN,58.058431
min,1000.000000,18.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,20.750000,20.750000,1.000000,NaN,NaN,NaN,0.000000
25%,5478.000000,33.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,1139.680000,361.180000,3.000000,NaN,NaN,NaN,7.615000
50%,10499.500000,49.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,2534.490000,463.960000,5.000000,NaN,NaN,NaN,51.700000
75%,15504.000000,65.000000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,4639.600000,791.190000,8.000000,NaN,NaN,NaN,93.842500
max,19998.000000,80.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,11396.800000,1139.680000,10.000000,NaN,NaN,NaN,292.770000

In [9]:
df.isna().sum()

Customer ID             0
Age                     0
Gender                  1
Loyalty Member          0
Product Type            0
SKU                     0
Rating                  0
Order Status            0
Payment Method          0
Total Price             0
Unit Price              0
Quantity                0
Purchase Date           0
Shipping Type           0
Add-ons Purchased    4868
Add-on Total            0
dtype: int64

In [25]:
import re

# Ensure column names are in the expected format before use
df.columns = [
    re.sub(r'_{2,}', '_', col.lower().replace(' ', '_').replace('-', '_'))
    for col in df.columns
]

df['add_ons_purchased'] = df.groupby('product_type')['add_ons_purchased'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'None'))
df.isna().sum()

customer_id                 0
age                         0
gender                      1
loyalty_member              0
product_type                0
sku                         0
rating                      0
order_status                0
payment_method              0
total_price                 0
unit_price                  0
quantity                    0
purchase_date               0
shipping_type               0
add_ons_purchased           0
add_on_total                0
age_group                   0
frequency_purchase_month    0
dtype: int64

In [11]:
# Convert column names to lowercase, replace spaces and hyphens with underscores,
# then replace any sequence of multiple underscores with a single underscore.
df.columns = [
    re.sub(r'_{2,}', '_', col.lower().replace(' ', '_').replace('-', '_'))
    for col in df.columns
]
# Display the new column names
df.columns

Index(['customer_id', 'age', 'gender', 'loyalty_member', 'product_type', 'sku',
       'rating', 'order_status', 'payment_method', 'total_price', 'unit_price',
       'quantity', 'purchase_date', 'shipping_type', 'add_ons_purchased',
       'add_on_total'],
      dtype='str')

In [12]:
#create a new column age_group
labels = ['Young Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=3, labels=labels)

In [13]:
df[['age','age_group']].head(10)

   age    age_group
0   53  Middle-aged
1   53  Middle-aged
2   41  Middle-aged
3   41  Middle-aged
4   75       Senior
5   41  Middle-aged
6   25  Young Adult
7   25  Young Adult
8   24  Young Adult
9   24  Young Adult

In [14]:
df[['purchase_date']].head(10)

  purchase_date
0    2024-03-20
1    2024-04-20
2    2023-10-17
3    2024-08-09
4    2024-05-21
5    2024-05-26
6    2024-01-30
7    2024-06-24
8    2023-10-03
9    2024-01-01

In [15]:
# create column frequency_purchase_month 

frequency_mapping = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}
df['frequency_purchase_month'] = pd.to_datetime(df['purchase_date']).dt.month

In [16]:
df[['purchase_date','frequency_purchase_month']].head(10)

  purchase_date  frequency_purchase_month
0    2024-03-20                         3
1    2024-04-20                         4
2    2023-10-17                        10
3    2024-08-09                         8
4    2024-05-21                         5
5    2024-05-26                         5
6    2024-01-30                         1
7    2024-06-24                         6
8    2023-10-03                        10
9    2024-01-01                         1

In [17]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in C:\Users\Janet Owiti\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\Users\Janet Owiti\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Janet Owiti\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Downloading psycopg2_binary-2.9.12-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 607.1 kB/s eta 0:00:04
   ------- -------------------------------- 0.5/2.8 MB 607.1 kB/s eta 0:00:04
   ----------- ---------------------------- 0.8/2.8 MB 706.6 kB/s eta 0:00:03
   -------------- ------------------------- 1.0/2.8 MB 737.7 kB/s eta 0:00:03
   ------------------ --------------------- 1.3/2.8 MB 838.0 kB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 913.9 kB/s eta 0:00:02
   ------------------------- -------------- 1.8/2.8 MB 985.3 kB/s eta 0:00:02
   --------------------------------- ------ 2.4/2.8 MB 1.1 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.8 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 1.2 MB/s  0:00:03
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [18]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = 'postgres'
password = '123456'
host = 'localhost'
port = '5432'
database = 'customer_behavior'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer_behavior"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"DataFrame loaded into PostgreSQL table: {table_name}")

DataFrame loaded into PostgreSQL table: customer_behavior